version: '3.4'

services:
  geminieducationapi.api:
    image: geminieducationapi
    build:
      context: .
      dockerfile: GeminiEducationAPI.API/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=GeminiEducationDB;User=sa;Password=MyStrongPassword123!;TrustServerCertificate=True
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - SA_PASSWORD=MyStrongPassword123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

